name: flutter_pokedex
description: "Code challenge para Flutter Developers."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.4 <4.0.0"

dependencies:
  cached_network_image: ^3.3.1
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_animator: ^3.2.2
  flutter_cache_manager: ^3.3.2
  get: ^4.6.6
  hive: ^2.2.3
  http: ^1.2.1
  json_annotation: ^4.9.0
  shared_preferences: ^2.2.3

dev_dependencies:
  build_runner: ^2.4.9
  flutter_lints: ^3.0.2
  flutter_test:
    sdk: flutter
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
